version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
    networks:
      - my-network
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge