spring:
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password:
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      show_sql: false
      format_sql: true
      ddl-auto: update
    open-in-view: true
    defer-datasource-initialization: false
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:h2:mem:mydb
    password:
    user: sa
