spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/mydb
    username: root
    password: root
  flyway:
    enabled: true
    url: jdbc:mysql://db:3306/mydb
    user: root
    password: root